---
  title: "Hi, I'm Selina"
---
  
  I'm a current master's student in Marine Biology at the University of New Hampshire in the <a href="https://quantmarineecolab.github.io/" >Quantitative Marine Ecology Lab (QMEL)</a> with Dr. Easton White.
  
  My research will collaborate with local shellfish farmers to use new technologies – specifically Arduino microcontrollers and sensors – to measure oyster behavioral responses and improve aquaculture outcomes. 

I earned bachelor’s degrees in Environmental Science and English from the University of Virginia in 2021 and developed a love for coastal ecology during my undergraduate research on <a href = "https://link.springer.com/article/10.1007/s12237-021-01039-5">blue crabs</a> at the Virginia Coast Reserve LTER. I most recently worked as a technician at the <a href = "https://serc.si.edu/labs/technology-in-ecology">Smithsonian Environmental Research Center</a> in Edgewater, MD, where I created data workflows, fabricated electronics, and maintained sensor networks for salt marsh climate change experiments. I'm excited to return to the marine ecology world with QMEL!

In my free time, I enjoy sewing quilts both big and small, playing Ultimate Frisbee, and learning about foraging.